Repository fiskaltrust/faq, pull requests merged in 2020-06, with the labels that each got.

#18 Create DE-corona-VAT-reduction-2020 [DE]
  qna/DE-corona-VAT-reduction-2020
Labels: waiting for review

#24 Add QNA about supported operation systems for DE
  qna/DE-operating-systems.md
Labels: waiting for review

#21 Add certified online TSEs QNA for DE
  qna/DE-certified-online-TSE.md
Labels: waiting for review

#22 Clarify if fiskaltrust is certified according to BSI TR-03153
  qna/DE-fiskaltrust-certified.md
Labels: waiting for review

#27 outages
  qna/DE-MW-Ausfall.md
  qna/DE-TSE-Ausfall.md
Labels: waiting for review

#26 add Q&A from current DE website
  qna/DE-MW-Ausfall.md
  qna/DE-Nichtbeanstandungsregelung.md
  qna/DE-TSE-Ausfall.md
  qna/DE-TSE-support.md
  qna/DE-alte-Kassen.md
Labels: in review

#23 Address special DSFinV-k VAT IDs > 1000
  qna/DE-special-VAT-cases.md
Labels: waiting for review

#6 Add Q&A set for issue #3 - start time
  examples/DE-action-start-de.md
  qna/DE-action-start-de.md
Labels: waiting for review

#32 Typos and update markdown links
  qna/DE-corona-VAT-reduction-2020.md
Labels: waiting for review

#29 Create new Q&A for AT-corona-USt-Senkung-Gastronomie-2020
  qna/AT-corona-USt-Senkung-Gastronomie-2020.md
Labels: done

#36 Update link to BMF-document
  qna/DE-corona-VAT-reduction-2020.md
Labels: waiting for review

#34 Answered 'How to extend Carefree products which expired beyond the grace period'
  qna/AT-carefree-extension-after-expired-grace-period.md
Labels: in review

#31 update FAQ from German Website
  images/20191122-ft-Belegmerkmale-DE-v0.5.pdf
  qna/DE-Export.md
  qna/DE-Rechnung-Beleg-Inhalte.md
  qna/DE-TSE-Ausfall.md
  qna/DE-TSE-support.md
  qna/DE-alte-Kassen.md
  qna/DE-corona-VAT-reduction-2020.md
  qna/DE-custom-datacenter-hosting.md
  qna/DE-was-macht-ft.md
Labels: in review

#61 add new meta tags
  README.md
Labels: waiting for review
